### ISSUE TITLE
Recipe Request: Vanilla Ice Cream

### ISSUE THREAD

**Issue by ssuess** [schollz/recursive-recipes#9]
**What recipe would you like to add?**
Vanilla Ice Cream

**Comment by schollz** [comment]
Done: https://recursive.recipes/recipe/vanilla-ice-cream

**Comment by schollz** [comment]
Your questions are good and get it something that I'm not sure how to tackle - recurring vs one-time cost. 

Cow and soil can presumably be used for many recipes. You buy them once and then use them over and over. The same is not true for other ingredients - once you use an egg then you can't use it again. Recurring costs could be calculated - but it becomes very complicated. You'd have to calculate how milk one cow would generate, and how much it would cost to maintain its life (food + medicine + housing). These are not impossible calculations, but hard, and I basically and assuming for now that they are ~$0 for the scale of the recipe. The same is true for the acre of land - you'd have to calculate how much the land costs / year (property taxes, upkeep), and how much food the land generates - again complicated. 

Also it matters how long you keep the particular thing (land/cow) - if you own it for 80 years its cost will be different than if you own it for 1. I'm also not sure how to factor this in to the above calculations - I don't want to prompt the user for how long they expect to have the cow for. But a reasonable averaging might be okay.

Vanilla plants aren't done - that should be no problem. I'm not sure about the alcohol, maybe it is a rounding issue. I'll look.
